INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ACCT501', 'Auditing', '94874');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARTS500', 'Contemporary Art Criticism', '98594');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARTS600', 'Contemporary Art and Technology', '97513');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BIOL610', 'Evolutionary Biology', '97252');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BIOL710', 'Marine Biology', '98937');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BUSN440', 'International Entrepreneurship', '94685');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BUSN450', 'Corporate Social Responsibility', '96970');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHEM501', 'Analytical Chemistry', '98736');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMM620', 'Communication Theory', '93306');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMM720', 'Media Ethics', '93639');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMP501', 'Computer Networks', '99382');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CRIM501', 'White-Collar Crime', '56152');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CRIM601', 'Forensic Science', '97627');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ECON601', 'Game Theory', '92840');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('EDUC610', 'E-Learning', '97468');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('EDUC710', 'Adult Learning', '98315');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENGL620', 'Literature and Film', '94008');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENVS501', 'Environmental Economics', '99784');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FINC601', 'Financial Risk Management', '94873');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FREN501', 'Francophone Culture', '96472');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GEOG501', 'Environmental Geography', '99519');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HIST610', 'Modern Europe', '91660');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HIST710', 'History of Science', '94335');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HRMG620', 'International Human Resource Management', '98281');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HRMG720', 'Strategic Human Resource Management', '91516');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('INFS502', 'Enterprise Systems', '95179');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MATH402', 'Complex Analysis', '96551');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MATH502', 'Topology', '96333');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MGMT620', 'Organizational Development', '99530');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MGMT720', 'Change Management', '95879');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MKTG520', 'Brand Management', '93225');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MKTG620', 'Marketing Research', '95073');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MUSC401', 'Music Performance', '93131');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MUSC501', 'Music Technology', '91971');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('NURS600', 'Healthcare Informatics', '97487');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('NURS700', 'Advanced Practice Nursing', '96787');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHIL401', 'Metaphysics', '98810');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHIL501', 'Epistemology', '54670');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHIL601', 'Philosophy of Mind', '96492');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHYS301', 'Modern Physics', '99375');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHYS401', 'Quantum Mechanics', '98645');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('POLS501', 'Comparative Politics', '93854');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('POLS601', 'Political Theory', '91428');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC402', 'Cognitive Psychology', '98759');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC502', 'Developmental Psychology', '98943');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC602', 'Personality Psychology', '93760');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('RELS301', 'Islam', '93982');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('RELS401', 'Hinduism', '96500');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('RELS501', 'Buddhism', '93010');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SOC401', 'Sociology of Deviance', '94511');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SOC501', 'Sociology of Race and Ethnicity', '94874');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SOC601', 'Sociology of Work', '98594');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SPAN301', 'Spanish Literature', '97513');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SPAN401', 'Latin American Literature', '97252');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('STAT401', 'Regression Analysis', '98937');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('STAT501', 'Time Series Analysis', '94685');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('STAT601', 'Bayesian Analysis', '96970');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('THEA400', 'Playwriting I', '98736');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('THEA500', 'Directing II', '93306');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('THEA600', 'Playwriting II', '93639');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ACCT301', 'Financial Accounting', '99382');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ACCT701', 'International Accounting', '91585');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ANTH301', 'Introduction to Anthropology', '97627');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ANTH501', 'Anthropology of Globalization', '92840');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARCH401', 'Architectural Design', '97468');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARCH601', 'Sustainable Architecture', '98315');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARTH501', 'Renaissance Art', '94008');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARTH701', 'Contemporary Art', '99784');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ASTR401', 'Astronomy', '94873');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ASTR601', 'Astrophysics', '96472');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BIOC401', 'Biochemistry', '99519');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BIOC601', 'Molecular Biology', '52075');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BTEC301', 'Biotechnology', '94335');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BTEC501', 'Industrial Biotechnology', '98281');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHEM301', 'General Chemistry', '91516');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHEM701', 'Organic Chemistry', '95179');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHIN301', 'Chinese Language and Culture', '96551');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHIN501', 'Chinese Literature', '96333');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CLAS301', 'Classical Mythology', '99530');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CLAS501', 'Ancient Philosophy', '59232');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMM501', 'Intercultural Communication', '93225');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMM701', 'Global Communication', '95073');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMP301', 'Computer Programming', '93131');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMP701', 'Big Data Analytics', '91971');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CSCI301', 'Computer Science I', '97487');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CSCI501', 'Computer Science II', '96787');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CULT501', 'Cultural Studies', '98810');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CULT701', 'Critical Theory', '94744');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ECON301', 'Microeconomics', '96492');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ECON501', 'Macroeconomics', '99375');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ELEC401', 'Electrical Engineering', '98645');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ELEC601', 'Digital Signal Processing', '93854');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENGL301', 'British Literature', '91428');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENGL501', 'American Literature', '98759');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENVS301', 'Environmental Science', '98943');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENVS701', 'Climate Change', '93760');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FINC301', 'Corporate Finance', '93982');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FREN301', 'French Language and Culture', '96500');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FREN701', 'French Literature', '93010');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GEOG301', 'Physical Geography', '94511');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GEOG701', 'Geographical Information Science', '94874');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GERM301', 'German Language and Culture', '98594');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GERM501', 'German Literature', '97513');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HIST301', 'World History', '97252');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HIST501', 'Canadian History', '98937');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HUMA501', 'Humanities and the Environment', '94685');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HUMA701', 'Digital Humanities', '96970');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('INFS301', 'Database Systems', '98736');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('INFS701', 'Business Intelligence', '93306');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ITAL301', 'Italian Language and Culture', '93639');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ITAL501', 'Italian Literature', '99382');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('JAPA301', 'Japanese Language and Culture', '91585');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('JAPA501', 'Japanese Literature', '97627');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('JOUR701', 'Investigative Journalism', '92840');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('KORE301', 'Korean Language and Culture', '97468');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('KORE501', 'Korean Literature', '98315');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('LAWS301', 'Contract Law', '94008');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('LAWS701', 'Intellectual Property Law', '99784');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MATH301', 'Calculus', '94873');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MATH501', 'Linear Algebra', '96472');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MGMT301', 'Principles of Management', '99519');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MGMT501', 'Organizational Behavior', '91660');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MKTG301', 'Marketing Fundamentals', '94335');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MKTG501', 'Consumer Behavior', '98281');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MUSC301', 'Music Theory', '91516');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MUSC701', 'Musicology', '95179');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('NURS301', 'Foundations of Nursing', '96551');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('NURS701', 'Nursing Leadership', '51772');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHIL301', 'Ethics', '99530');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHIL701', 'Philosophy of Law', '95879');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PHYS201', 'Classical Mechanics', '93225');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('POLS301', 'International Relations', '95073');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC301', 'Social Psychology', '93131');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC701', 'Neuropsychology', '91971');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('RELS201', 'Christianity', '97487');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('RELS701', 'Comparative Religion', '96787');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SOCI301', 'Sociological Theory', '98810');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SOCI701', 'Social Inequality', '94744');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SPAN201', 'Spanish Language and Culture', '96492');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('STAT201', 'Probability and Statistics', '99375');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('STAT701', 'Data Mining', '98645');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('THEA301', 'Acting I', '93854');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ACCT801', 'Financial Statement Analysis', '91428');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ANTH401', 'Cultural Anthropology', '98759');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ANTH801', 'Anthropology of Religion', '98943');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARCH501', 'Architectural History', '93760');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARCH801', 'Advanced Building Systems', '93982');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARTH401', 'Baroque Art', '96500');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ARTH801', 'Contemporary Art Theory', '93010');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ASTR501', 'Planetary Science', '94511');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ASTR801', 'Stellar Astrophysics', '94874');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BIOC501', 'Cell Biology', '98594');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BIOC801', 'Genomics and Bioinformatics', '97513');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BTEC401', 'Bioengineering', '97252');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('BTEC801', 'Bioprocess Engineering', '98937');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHEM401', 'Physical Chemistry', '94685');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHIN401', 'Chinese Cinema', '96970');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CHIN801', 'Classical Chinese', '98736');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CLAS401', 'Ancient History', '93306');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CLAS801', 'Greek Tragedy', '93639');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMM401', 'Media and Society', '99382');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMM801', 'Crisis Communication', '91585');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('COMP801', 'Cloud Computing', '97627');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CSCI401', 'Artificial Intelligence', '92840');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CSCI801', 'Computer Graphics', '97468');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CULT401', 'Globalization and Culture', '98315');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('CULT801', 'Postcolonial Theory', '94008');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ECON801', 'Econometrics', '99784');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ELEC501', 'Signals and Systems', '94873');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ELEC801', 'Power Electronics', '96472');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENGL801', 'Literary Theory', '99519');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ENVS801', 'Environmental Law', '91660');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FINC401', 'Investments', '94335');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FINC801', 'Derivatives Markets', '98281');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('FREN801', 'French Linguistics', '91516');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GEOG401', 'Human Geography', '95179');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GERM401', 'German Cinema', '56190');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('GERM801', 'German Linguistics', '96333');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HIST401', 'Medieval History', '99530');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HIST801', 'Twentieth-Century Europe', '95879');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HUMA401', 'Cultural Diversity', '93225');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('HUMA801', 'Digital Culture', '95073');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('INFS401', 'Web Application Development', '93131');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ITAL401', 'Italian Cinema', '91971');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('ITAL801', 'Italian Linguistics', '97487');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('JAPA401', 'Japanese Cinema', '96787');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('JAPA801', 'Advanced Japanese Language', '98810');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('JOUR801', 'Media Law and Ethics', '94744');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('KORE401', 'Korean Cinema', '96492');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('LATN401', 'Latin Language and Literature', '99375');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('LATN801', 'Roman History', '98645');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MATH401', 'Mathematical Analysis', '93854');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MGMT801', 'Strategic Management', '91428');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('MUHI401', 'Music History', '98759');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('POLS801', 'Political Philosophy', '98943');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC401', 'Abnormal Psychology', '93760');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('PSYC801', 'Cognitive Neuroscience', '93982');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SOC801', 'Social Movements', '96500');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('SPAN801', 'Advanced Spanish Composition', '93010');
INSERT INTO yvle.Course (course_id, Course_Name, Course_admin) VALUES ('WGS401', 'Women and Gender Studies', '94511');